#!/bin/sh

set -e

srcdir=src

# Use defaults now. Hopefully nobody uses really old versions
# anymore,
ACLOCAL="aclocal"
AUTOMAKE="automake"
AUTOCONF="autoconf"
AUTOHEADER="autoheader"


set -x
(
    $ACLOCAL
    $AUTOCONF
    [ -d config-aux ] || mkdir config-aux
    $AUTOMAKE -a -c

    cd $srcdir
    $ACLOCAL
    $AUTOHEADER
    $AUTOCONF
    $AUTOMAKE -a -c
    cd ..

    cd libiberty
    $AUTOCONF
    cd ..

    cd libcpp
    $ACLOCAL -I ../config-aux
    $AUTOCONF
    cd ..
)
rm -f config.cache $srcdir/config.cache
