#!/bin/sh
killall -q avarice
echo $1
if [ "$1" != "" ] ; then
  avr-objcopy -O binary $1 /tmp/av$$.bin
  avarice $AVARICE_ARGS -f /tmp/av$$.bin localhost 6423 --detach
  rm -f /tmp/av$$.bin
else
  avarice $AVARICE_ARGS localhost 6423 --detach
fi

