#define nw_struct nx_struct
#define nw_union nx_union
#define nw_int8_t nx_int8_t
#define nw_int16_t nx_int16_t
#define nw_int32_t nx_int32_t
#define nw_int64_t nx_int64_t
#define nw_uint8_t nx_uint8_t
#define nw_uint16_t nx_uint16_t
#define nw_uint32_t nx_uint32_t
#define nw_uint64_t nx_uint64_t
